# Generated by Django 3.2.12 on 2022-12-16 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10)),
                ('firstname', models.CharField(max_length=125)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('bitrh_date', models.DateField(blank=True, null=True)),
                ('anni_date', models.DateField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('type', models.CharField(choices=[('text', 'text'), ('int', 'int'), ('date', 'date'), ('largetext', 'largetext'), ('numeric', 'numeric')], max_length=125)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_value', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.contact')),
                ('custom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.custom')),
            ],
        ),
    ]
