# Generated by Django 3.2.12 on 2022-12-16 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.RenameField(
            model_name='custom',
            old_name='user_id',
            new_name='userid',
        ),
    ]
