# Generated by Django 3.2.12 on 2022-12-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20221219_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='type',
            field=models.CharField(choices=[('text', 'text'), ('int', 'int'), ('date', 'date'), ('largetext', 'largetext'), ('number', 'number')], max_length=125),
        ),
    ]
